---
# tasks file for ansible-prometheus-node-exporter

# Pre-install create user, dirs
- name: Prometheus group created
  group:
    name: '{{ PROMETHEUS_NODE_EXPORTER_GROUP }}'
    state: present

- name: Prometheus user created
  user:
    name: '{{ PROMETHEUS_NODE_EXPORTER_USER }}'
    group: '{{ PROMETHEUS_NODE_EXPORTER_GROUP }}'
    createhome: false
    shell: '/sbin/nologin'
    state: 'present'

- name: Prometheus Node Exporter directories created
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: '{{ PROMETHEUS_NODE_EXPORTER_USER }}'
    group: '{{ PROMETHEUS_NODE_EXPORTER_GROUP }}'
    mode: 'u=rwx,g=rx,o='
  with_items: '{{ PROMETHEUS_NODE_EXPORTER_DIRS.values() }}'

- name: Configure RAID monitoring with StorCLI
  include: 'monitor_raid_storcli.yml'
  when: 'PROMETHEUS_NODE_EXPORTER_MONITOR_STORCLI == true'

- name: Prometheus Node Exporter binaries downloaded
  get_url:
    url: 'https://github.com/prometheus/node_exporter/releases/download/v{{ PROMETHEUS_NODE_EXPORTER_VERSION }}/{{ PROMETHEUS_NODE_EXPORTER_DIR_NAME }}.tar.gz'
    dest: '/tmp/{{ PROMETHEUS_NODE_EXPORTER_DIR_NAME }}.tar.gz'
    checksum: 'sha256:{{ PROMETHEUS_NODE_EXPORTER_PACKAGE_CHECKSUM }}'

- name: Prometheus Node Exporter binaries extracted
  unarchive:
    src: '/tmp/{{ PROMETHEUS_NODE_EXPORTER_DIR_NAME }}.tar.gz'
    remote_src: true
    dest: '{{ PROMETHEUS_NODE_EXPORTER_DIRS.PROMETHEUS_BINARIES_DIR }}'

- name: Prometheus Node Exporter systemd unit file templated
  template:
    src: 'prometheus-node-exporter.service.j2'
    dest: '/lib/systemd/system/prometheus-node-exporter.service'
  when: 'ansible_service_mgr == "systemd"'

- name: Prometheus Node Exporter upstart file templated
  template:
    src: 'prometheus-node-exporter.conf.j2'
    dest: '/etc/init/prometheus-node-exporter.conf'
  when: 'ansible_service_mgr == "upstart"'

- name: Prometheus Node Exporter service enabled and restarted (systemd)
  systemd:
    daemon_reload: true
    name: 'prometheus-node-exporter'
    enabled: true
    state: 'restarted'
  when: 'ansible_service_mgr == "systemd"'

- name: Upstart configuration reloaded
  command: 'initctl reload-configuration'
  when: 'ansible_service_mgr == "upstart"'

- name: Prometheus Node Exporter service enabled and restarted (upstart)
  service:
    name: 'prometheus-node-exporter'
    enabled: true
    state: 'restarted'
  when: 'ansible_service_mgr == "upstart"'


- name: Hole poked through firewall
  ufw:
    rule: 'allow'
    port: '{{ PROMETHEUS_NODE_EXPORTER_PORT }}'
    proto: 'tcp'
  when: 'PROMETHEUS_NODE_EXPORTER_MANAGE_FW == true'
